### ISSUE TITLE
Investigate request preview formatting

### ISSUE THREAD

**Issue by gbp** [mysociety/foi-for-councils#107]
Report from catchup call that formatting of a request is lost and compacted. No screen shots but worth taking a look.

**Comment by garethrees** [comment]
Looks okay as far as I can see?

![screen shot 2018-05-23 at 09 33 32](https://user-images.githubusercontent.com/282788/40412870-62652fcc-5e6c-11e8-81de-49f4df3a1990.png)

I wonder if they mean "I pasted from Word and now I don't have bold and italics"?

**Comment by garethrees** [comment]
Closing as we can't see any problems here. We'll ask for more feedback on the catchup call and reopen if new information comes to light.
