### ISSUE TITLE
No reference number returned when sending requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#207]
On staging, I noticed that in Chrome and Safari, we never get past the loading spinner on the `/sent` page:

![hackney-sent-no-reference](https://user-images.githubusercontent.com/282788/48771865-80932800-ecba-11e8-8c07-f15ed8420f9f.gif)

## How to reproduce locally

At the moment we can't `POST` to the sandbox API. That's fine for the purposes here; just stub it:

```diff
diff --git a/app/services/deliver_submission.rb b/app/services/deliver_submission.rb
index e687b83..aa87cba 100644
--- a/app/services/deliver_submission.rb
+++ b/app/services/deliver_submission.rb
@@ -8,10 +8,10 @@ class DeliverSubmission < SimpleDelegator
   delegate :contact, to: :foi_request

   def call
-    request = Infreemation::Request.create!(attributes)
+    # request = Infreemation::Request.create!(attributes)
     update(
       state: Submission::DELIVERED,
-      reference: request.attributes[:ref]
+      reference: 'FOI-TEST' #request.attributes[:ref]
     )
   end
```

Now run the app in _production mode_:

```sh
RAILS_ENV=production bin/rake assets:precompile
RAILS_SERVE_STATIC_FILES=1 RAILS_ENV=production shoreman
```

Submit a request.

Its notable that when running in development mode, I get `VM858:1 XHR finished loading: GET "http://192.168.33.143:3000/foi/request/sent.json".` log lines as we poll for the submission ref. I don’t get any console log output on the staging site, or while running in production mode locally.

If I paste `$('.js-async-delivery-status').each(checkDeliveryStatus);` in to the console on staging, while the loading spinner is displayed, it _does_ poll `/sent.json` and then renders the reference number on to the page. Looks like its having a problem actually doing the polling.

My suspicion is that we never actually call `checkDeliveryStatus`, because of some loading issue around https://github.com/mysociety/foi-for-councils/blob/develop/app/assets/javascripts/application/async-delivery-status.js#L45-L47

## Fix

We've had a similar issue before: https://github.com/mysociety/foi-for-councils/issues/180.

https://github.com/turbolinks/turbolinks/issues/212#issuecomment-424625446 suggests not to use `async: true`. I don't really understand this enough to make much of an informed judgement, but it does seem to fix the problem:

Applying the following diff and restarting the server fixes the issue.

```diff
diff --git a/app/views/layouts/application.html.erb b/app/views/layouts/application.html.erb
index 60a63b9..8b9dc78 100644
--- a/app/views/layouts/application.html.erb
+++ b/app/views/layouts/application.html.erb
@@ -6,7 +6,7 @@
     <%= javascript_include_tag 'application-ie9', async: true, 'data-turbolinks-track': 'reload' %>
   <![endif]-->
   <!--[if gt IE 9]><!-->
-    <%= javascript_include_tag 'application', async: true, 'data-turbolinks-track': 'reload' %>
+    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <!--<![endif]-->
 <% end %>
```

**Comment by gbp** [comment]
As I understand it the JS should loaded asynchronously to improve page load speeds and better page rank.

It seems strange that its not recommended by Turbolinks but I kinda understand why, https://github.com/turbolinks/turbolinks/issues/28#issuecomment-189898761 explains the issue well.

In order of preference, I would try:

1. changing `async` to `defer` (which won't work for the IE9 JS)
2. changing `turbolinks:load` event listener in `async-delivery-status.js` so the JS runs for a different event, maybe `$(document).ready` would work?
3. remove async as its not going to have a huge impact on our small files anyway.
