### ISSUE TITLE
Drop use of Google+ API

### ISSUE THREAD

**Issue by gbp** [mysociety/foi-for-councils#223]
This was used by [omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2), we should upgrade to 0.6.0 - see https://github.com/zquestz/omniauth-google-oauth2/issues/340

**Comment by gbp** [comment]
https://groups.google.com/a/mysociety.org/forum/#!topic/clientsupport-council-foi/5CiSVejJtC0

**Comment by garethrees** [comment]
Noting https://github.com/zquestz/omniauth-google-oauth2/compare/v0.5.4...master#diff-04c6e90faac2675aa89e2176d2eec7d8L10 in case we need to make any config changes
