### ISSUE TITLE
[ERROR] (JSON::GeneratorError) "source sequence is illegal/malformed utf-8"

### ISSUE THREAD

**Issue by gbp** [mysociety/foi-for-councils#228]
From: https://groups.google.com/a/mysociety.org/forum/#!topic/cron-foi-for-councils/CVQmgIpFjNo

```
A JSON::GeneratorError occurred in background at 2019-04-01 06:33:15 UTC :
       "enqueued_at"=>1554100395.2388668,
       "error_message"=>"source sequence is illegal/malformed utf-8",
       "error_class"=>"JSON::GeneratorError",
       "failed_at"=>1554084000.690861,
       "retry_count"=>9,
       "retried_at"=>1554093586.5809407},
     :jobstr=>
      "{\"class\":\"ImportDisclosureLogWorker\",\"args\":[\"all\"],\"queue\":\"default\",\"retry\":true,\"jid\":\"ffd2bc803deff506a6dc7830\",\"created_at\":1554084000.2772253,\"enqueued_at\":1554100395.2388668,\"error_message\":\"source sequence is illegal/malformed utf-8\",\"error_class\":\"JSON::GeneratorError\",\"failed_at\":1554084000.690861,\"retry_count\":9,\"retried_at\":1554093586.5809407}"}}
```

These occurred before and it seems to be invalid characters in the JSON return from the API. See: https://groups.google.com/a/mysociety.org/forum/#!searchin/clientsupport-council-foi/json%7Csort:date/clientsupport-council-foi/HnrNVojRxnE/cm5uuhy9CQAJ

**Comment by garethrees** [comment]
Staging site at least, but yeah I checked the sidekiq queue and it looks like it'll continue to retry. Worth getting in touch with Infreemation I think.

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/foi-for-councils/issues/326
