### ISSUE TITLE
Disclosure log link is 404

### ISSUE THREAD

**Issue by gbp** [mysociety/foi-for-councils#287]
https://github.com/mysociety/foi-for-councils/blob/7ee2dbdf94d606b16d861ba60e138faa7ef3cc81/app/views/foi/requests/index.html.erb#L14

Should we link directly to https://foi.infreemation.co.uk/hackney/ ?

**Comment by garethrees** [comment]
Someone external to Hackney noticed this https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/Wm235cTfHrc – decided to make a PR to get it fixed https://github.com/mysociety/foi-for-councils/pull/288.
