### ISSUE TITLE
Update link to disclosure log

### ISSUE THREAD

**Issue by garethrees** [mysociety/foi-for-councils#410]

**Comment by gbp** [comment]
I think these are the correct links:

UAT: https://uatportal.icasework.com/cases?&public=true&byCaseType=false&byKeyword=true&max=20&organisation=hackney&title=Hackney%20Council%20Disclosure%20Log&Style=NOHEADER

Production: https://hackneyportal.icasework.com/cases?&public=true&byCaseType=false&byKeyword=true&max=20&title=Hackney%20Council%20Disclosure%20Log
